version: '3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: web
    hostname: web
    # command: python /code/manage.py makemigrations
    # command: python /code/manage.py migrate
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: /web-entrypoint.sh
    volumes:
      - ./static:/code/static
      - ./logs:/code/logs
    ports:
      - "8080:8000"

volumes:
  postgres_data: